sudo: required

group: deprecated-2017Q2

language: node_js

node_js: 6.9.5

services:
  - docker

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost
    - dev-controller
    - kubernetes.default

before_script:
  - npm install -g grunt-cli
  - docker pull alpine:latest && docker pull soajsorg/soajs:latest
  - docker run -d --volume=/:/rootfs:ro --volume=/sys:/sys:rw --volume=/var/lib/docker/:/var/lib/docker:rw --volume=/var/lib/kubelet/:/var/lib/kubelet:rw --volume=/var/run:/var/run:rw -p 8080:80 --net=host --pid=host --privileged ameerfaraj/hyperkube /hyperkube kubelet --containerized --hostname-override=127.0.0.1 --require-kubeconfig --pod-manifest-path=/etc/kubernetes/manifests --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --allow-privileged --v=2
  - sudo curl -sSL "http://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl" > ./kubectl
  - sudo mv ./kubectl /usr/local/bin/
  - sudo chmod +x /usr/local/bin/kubectl
  - kubectl config set-cluster travis --server=http://localhost:8080
  - kubectl config set-context travis --cluster=travis
  - kubectl config use-context travis
  - sudo cp $HOME/.kube/config /var/lib/kubelet/kubeconfig
  - while [ $(kubectl get nodes | grep 127.0.0.1 | grep Ready | wc -l) -eq 0 ]; do sleep 1; done

script:
  - grunt coverage
